name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install flet
        run: pip install flet
        
      - name: Build APK
        run: |
          export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2048m"
          flet build apk
